# yaml-language-server: $schema=vendor/symfony/dependency-injection/Loader/schema/services.schema.json
services:
  database:
    image: mysql:8.0
    environment:
      # Name der Datenbank
      MYSQL_DATABASE: endlech
      # Passwort für den Benutzer 'root'
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 5

volumes:
  database_data:
